name: Test Builds
on:
  push:
    branches:
      - master
      - v[0-9].[0-9]**
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"
      - "**.ini"
      - "**.wrap"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"
      - "**.ini"
      - "**.wrap"

env:
  MESON_VERSION: '0.56.2'
  EM_VERSION: '3.1.5'
  EM_CACHE_FOLDER: 'emsdk'
  TAISEI_NOPRELOAD: 0
  TAISEI_PRELOAD_REQUIRED: 1

jobs:
  windows-test-build:
    name: Windows (x64)
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    container: mstorsjo/llvm-mingw:20210423 # cross-compiler with mingw
    steps:
    - name: Install Tools
      run: >
        apt update || true

        apt install -y -qq software-properties-common

        add-apt-repository ppa:git-core/ppa -y

        apt install -y -qq
        python3-docutils
        python3-pip
        git
        nsis

        pip3 install
        meson==${{ env.MESON_VERSION }}
        ninja
        zstandard

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure Taisei (Meson)
      run: >
        meson setup build/
        --cross-file misc/ci/windows-llvm_mingw-x86_64-build-test-ci.ini
        --prefix=$(pwd)/build-test

    - name: Build
      run: |
        meson compile -C build/ --verbose
        meson install -C build/
        tar -cf win.tar build/src

    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: taisei_windows_fail_log
        path: win.tar
